INSERT INTO room (current_id, id, name)
VALUES (1, 1, 'Room for Romanico'),
       (2, 2, 'Room for Gotico'),
       (3, 3, 'Room for Umanesimo'),
       (4, 4, 'Room for Rinascimento'),
       (5, 5, 'Room for Barocco'),
       (6, 6, 'Room for Rococo'),
       (7, 7, 'Room for Neoclassicismo'),
       (8, 8, 'Room for Romanticismo'),
       (9, 9, 'Room for Realismo'),
       (10, 10, 'Room for Impressionismo'),
       (11, 11, 'Room for Post-Impressionismo'),
       (12, 12, 'Room for Giapposismo'),
       (13, 13, 'Room for Art Nouveau'),
       (14, 14, 'Room for Fauvismo'),
       (15, 15, 'Room for Cubismo'),
       (16, 16, 'Room for Futurismo'),
       (17, 17, 'Room for Espressionismo'),
       (18, 18, 'Room for Surrealismo'),
       (19, 19, 'Room for Astrattismo');