INSERT INTO tag (id, name) VALUES
                                (1, 'Madonna'),
                                (2, 'Religioso'),
                                (3, 'Gesù'),
                                (4, 'Angeli'),
                                (5, 'Santi'),
                                (6, 'Crocifisso'),
                                (7, 'Trinità'),
                                (8, 'Diavolo'),
                                (9, 'Pala'),
                                (10, 'Arcangelo'),
                                (11, 'Sacro'),
                                (12, 'Animali'),
                                (13, 'Resurrezione'),
                                (14, 'Uovo'),
                                (15, 'Fantasy'),
                                (16, 'Ritratto femminile'),
                                (17, 'Cibo'),
                                (18, 'Morte'),
                                (19, 'Chiaroscuro'),
                                (20, 'Frutta'),
                                (21, 'Mitologia'),
                                (22, 'Nudo'),
                                (23, 'Autoritratto'),
                                (24, 'Mare'),
                                (25, 'Ritratto Maschile'),
                                (26, 'Natura'),
                                (27, 'Guerra'),
                                (28, 'Fuoco'),
                                (29, 'Bacio'),
                                (30, 'Quotidiano'),
                                (31, 'Denuncia sociale'),
                                (32, 'Luce'),
                                (33, 'Serie di quadri'),
                                (34, 'Alcool'),
                                (35, 'Danza'),
                                (36, 'Notte'),
                                (37, 'Fiori'),
                                (38, 'Natura morta'),
                                (39, 'Colori Vivaci'),
                                (40, 'Paesaggio'),
                                (41, 'Figure Geometriche'),
                                (42, 'Musica'),
                                (43, 'Architettura'),
                                (44, 'Sentimenti'),
                                (45, 'Sogni'),
                                (46, 'Italia'),
                                (47, 'Francia'),
                                (48, 'Olanda'),
                                (49, 'Giappone'),
                                (50, 'Germania'),
                                (51, 'Spagna'),
                                (52, 'Belgio'),
                                (53, 'Russia'),
                                (54, 'Olio su tela'),
                                (55, 'Pittura su rame'),
                                (56, 'Acquerello su carta'),
                                (57, 'Affresco'),
                                (58, 'Pittura su tavola'),
                                (59, 'Disegno a matita'),
                                (60, 'Tempera su tavola'),
                                (61, 'Inchiostro su carta'),
                                (62, 'Romanico'),
                                (63, 'Gotico'),
                                (64, 'Umanesimo'),
                                (65, 'Rinascimento'),
                                (66, 'Barocco'),
                                (67, 'Rococo'),
                                (68, 'Neoclassicismo'),
                                (69, 'Romanticismo'),
                                (70, 'Realismo'),
                                (71, 'Impressionismo'),
                                (72, 'Post-Impressionismo'),
                                (73, 'Giapposismo'),
                                (74, 'Art Nouveau'),
                                (75, 'Fauvismo'),
                                (76, 'Cubismo'),
                                (77, 'Futurismo'),
                                (78, 'Espressionismo'),
                                (79, 'Surrealismo'),
                                (80, 'Astrattismo');